/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hyperskill.gradleapp;

import com.diogonunes.jcdp.color.ColoredPrinter;
import com.diogonunes.jcdp.color.api.Ansi;

public class App {
    public void getGreeting() {
    	ColoredPrinter printer = new ColoredPrinter
		.Builder(1, false).build();

	printer.print("Hello colorful World!", Ansi.Attribute.BOLD, Ansi.FColor.BLUE, Ansi.BColor.WHITE);
    
	return;
    }



    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
	new App().getGreeting();
    }
}
